import Head from 'next/head';
// import { Inter } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] });

const Home = () => (
  <>
    <Head>
      <title>SJCET Lab Management System</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main />
  </>
);

export default Home;
