const timetable = {
  days: [
    {
      day: 'Monday',
      periods: [
        {
          id: 'M0',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '9:00AM - 9:55AM',
        },
        {
          id: 'M1',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '10:00AM - 10:55AM',
        },
        {
          id: 'M2',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '11:10AM - 12:00PM',
        },
        {
          id: 'M3',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '12:00PM - 12:45PM',
        },
        {
          id: 'M4',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '01:35PM - 02:30PM',
        },
        {
          id: 'M5',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '03:35PM - 04:30PM',
        },
      ],
    },
    {
      day: 'Tuesday',
      periods: [
        {
          id: 'T0',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '9:00AM - 9:55AM',
        },
        {
          id: 'T1',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '10:00AM - 10:55AM',
        },
        {
          id: 'T2',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '11:10AM - 12:00PM',
        },
        {
          id: 'T3',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '12:00PM - 12:45PM',
        },
        {
          id: 'T4',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '01:35PM - 02:30PM',
        },
        {
          id: 'T5',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '03:35PM - 04:30PM',
        },
      ],
    },
    {
      day: 'Wednessday',
      periods: [
        {
          id: 'W0',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '9:00AM - 9:55AM',
        },
        {
          id: 'W1',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '10:00AM - 10:55AM',
        },
        {
          id: 'W2',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '11:10AM - 12:00PM',
        },
        {
          id: 'W3',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '12:00PM - 12:45PM',
        },
        {
          id: 'W4',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '01:35PM - 02:30PM',
        },
        {
          id: 'W5',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '03:35PM - 04:30PM',
        },
      ],
    },
    {
      day: 'Thursday',
      periods: [
        {
          id: 'TH0',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '9:00AM - 9:55AM',
        },
        {
          id: 'TH1',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '10:00AM - 10:55AM',
        },
        {
          id: 'TH2',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '11:10AM - 12:00PM',
        },
        {
          id: 'TH3',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '12:00PM - 12:45PM',
        },
        {
          id: 'TH4',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '01:35PM - 02:30PM',
        },
        {
          id: 'TH5',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '03:35PM - 04:30PM',
        },
      ],
    },
    {
      day: 'Friday',
      periods: [
        {
          id: 'F0',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '9:00AM - 9:55AM',
        },
        {
          id: 'F1',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '10:00AM - 10:55AM',
        },
        {
          id: 'F2',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '11:10AM - 12:00PM',
        },
        {
          id: 'F3',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '12:00PM - 12:45PM',
        },
        {
          id: 'F4',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '01:35PM - 02:30PM',
        },
        {
          id: 'F5',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '03:35PM - 04:30PM',
        },
      ],
    },
    {
      day: 'Saturday',
      periods: [
        {
          id: 'S0',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '9:00AM - 9:55AM',
        },
        {
          id: 'S1',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '10:00AM - 10:55AM',
        },
        {
          id: 'S2',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '11:10AM - 12:00PM',
        },
        {
          id: 'S3',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '12:00PM - 12:45PM',
        },
        {
          id: 'S4',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '01:35PM - 02:30PM',
        },
        {
          id: 'S5',
          periodName: 'Java Lab',
          inCharge: 'Smitha Jacob',
          semester: 'S6',
          branch: 'CSEB',
          timing: '03:35PM - 04:30PM',
        },
      ],
    },
  ],
};

export default timetable;
