const teacherTimetable = {
  days: [
    {
      periods: [
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
      ],
    },
    {
      periods: [
        {
          periodName: 'Java Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
      ],
    },
    {
      periods: [
        {
          periodName: 'LSD Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
      ],
    },
    {
      periods: [
        {
          periodName: 'Network Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
      ],
    },
    {
      periods: [
        {
          periodName: 'OS Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
      ],
    },
    {
      periods: [
        {
          periodName: 'Free',
          semester: '',
          branch: '',
          batch: '',
          venue: '',
          roomNo: '',
        },
        {
          periodName: 'Free',
          semester: '',
          branch: '',
          batch: '',
          venue: '',
          roomNo: '',
        },
        {
          periodName: 'Free',
          semester: '',
          branch: '',
          batch: '',
          venue: '',
          roomNo: '',
        },
        {
          periodName: 'Free',
          semester: '',
          branch: '',
          batch: '',
          venue: '',
          roomNo: '',
        },
        {
          periodName: 'Free',
          semester: '',
          branch: '',
          batch: '',
          venue: '',
          roomNo: '',
        },
        {
          periodName: 'Free',
          semester: '',
          branch: '',
          batch: '',
          venue: '',
          roomNo: '',
        },
      ],
    },
  ],
};

export default teacherTimetable;
