const teacherTimetable = {
  days: [
    {
      periods: [
        {
          id: 'M0',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'M1',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'M2',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'M3',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'M4',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'M5',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
      ],
    },
    {
      periods: [
        {
          id: 'T0',
          periodName: 'Java Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'T1',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'T2',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'T3',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'T4',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'T5',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
      ],
    },
    {
      periods: [
        {
          id: 'W0',
          periodName: 'LSD Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'W1',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'W2',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'W3',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'W4',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'W5',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
      ],
    },
    {
      periods: [
        {
          id: 'TH0',
          periodName: 'Network Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'TH1',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'TH2',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'TH3',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'TH4',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'TH5',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
      ],
    },
    {
      periods: [
        {
          id: 'F0',
          periodName: 'OS Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'F1',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'F2',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'F3',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'F4',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
        {
          id: 'F5',
          periodName: 'Data Structures Lab',
          semester: 'S6',
          branch: 'CSEB',
          batch: '1',
          venue: 'Programming Lab',
          roomNo: 'MTB 209',
        },
      ],
    },
    {
      periods: [
        {
          id: 'S0',
          periodName: 'Free',
          semester: '',
          branch: '',
          batch: '',
          venue: '',
          roomNo: '',
        },
        {
          id: 'S1',
          periodName: 'Free',
          semester: '',
          branch: '',
          batch: '',
          venue: '',
          roomNo: '',
        },
        {
          id: 'S2',
          periodName: 'Free',
          semester: '',
          branch: '',
          batch: '',
          venue: '',
          roomNo: '',
        },
        {
          id: 'S3',
          periodName: 'Free',
          semester: '',
          branch: '',
          batch: '',
          venue: '',
          roomNo: '',
        },
        {
          id: 'S4',
          periodName: 'Free',
          semester: '',
          branch: '',
          batch: '',
          venue: '',
          roomNo: '',
        },
        {
          id: 'S5',
          periodName: 'Free',
          semester: '',
          branch: '',
          batch: '',
          venue: '',
          roomNo: '',
        },
      ],
    },
  ],
};

export default teacherTimetable;
