import { TimeTableByDay } from '@/types/UserData.d';

const timetableData: TimeTableByDay[] = [
  {
    day: 'Monday',
    periods: [
      {
        id: 'M0',
        periodName: 'Compiler Design',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '1',
        venue: null,
        roomNo: null,
        inCharge: null,
      },
      {
        id: 'M1',
        periodName: 'Operating Systems',
        semester: 'S4',
        branch: 'CSEA',
        periodNo: '2',
        venue: null,
        roomNo: null,
        inCharge: null,
      },
      {
        id: 'M2',
        periodName: 'Compiler Design',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '3',
        venue: null,
        roomNo: null,
        inCharge: null,
      },
      {
        id: 'M3',
        periodName: 'Operating Systems',
        semester: 'S4',
        branch: 'CSEB',
        periodNo: '4',
        venue: null,
        roomNo: null,
        inCharge: null,
      },
      {
        id: 'M4',
        periodName: 'OS Lab',
        semester: 'S4',
        branch: 'CSEB',
        periodNo: '5',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'M5',
        periodName: 'OS Lab',
        semester: 'S4',
        branch: 'CSEB',
        periodNo: '6',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: [
          { inChargeID: '0101', name: 'Ashley Miss' },
          { inChargeID: '0102', name: 'Angitha' },
        ],
      },
    ],
  },
  {
    day: 'Tuesday',
    periods: [
      {
        id: 'T0',
        periodName: 'Java Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '1',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'T1',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '2',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'T2',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '3',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'T3',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '4',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'T4',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '5',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'T5',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '6',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
    ],
  },
  {
    day: 'Wednesday',
    periods: [
      {
        id: 'W0',
        periodName: 'LSD Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '1',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'W1',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '2',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'W2',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '3',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'W3',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '4',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'W4',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '5',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'W5',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '6',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
    ],
  },
  {
    day: 'Thursday',
    periods: [
      {
        id: 'TH0',
        periodName: 'Network Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '1',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'TH1',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '2',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'TH2',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '3',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'TH3',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '4',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'TH4',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '5',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'TH5',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '6',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
    ],
  },
  {
    day: 'Friday',
    periods: [
      {
        id: 'F0',
        periodName: 'OS Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '1',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'F1',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '2',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'F2',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '3',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'F3',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '4',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'F4',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '5',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
      {
        id: 'F5',
        periodName: 'Data Structures Lab',
        semester: 'S6',
        branch: 'CSEB',
        periodNo: '6',
        venue: 'Programming Lab',
        roomNo: 'MTB 209',
        inCharge: null,
      },
    ],
  },
  {
    day: 'Saturday',
    periods: [
      {
        id: 'S0',
        periodName: 'Free',
        semester: null,
        branch: null,
        periodNo: '1',
        venue: null,
        roomNo: null,
        inCharge: null,
      },
      {
        id: 'S1',
        periodName: null,
        semester: null,
        branch: null,
        periodNo: '2',
        venue: null,
        roomNo: null,
        inCharge: null,
      },
      {
        id: 'S2',
        periodName: null,
        semester: null,
        branch: null,
        periodNo: '3',
        venue: null,
        roomNo: null,
        inCharge: null,
      },
      {
        id: 'S3',
        periodName: null,
        semester: null,
        branch: null,
        periodNo: '4',
        venue: null,
        roomNo: null,
        inCharge: null,
      },
      {
        id: 'S4',
        periodName: null,
        semester: null,
        branch: null,
        periodNo: '5',
        venue: null,
        roomNo: null,
        inCharge: null,
      },
      {
        id: 'S5',
        periodName: null,
        semester: null,
        branch: null,
        periodNo: '6',
        venue: null,
        roomNo: null,
        inCharge: null,
      },
    ],
  },
];

export default timetableData;
