import { TimeTableByDay } from '@/types/UserData.d';

const timetableData: TimeTableByDay[] = [
  {
    day: 'Monday',
    periods: [
      {
        id: 'M0',
        periodName: 'Compiler Design',
        semester: 6,
        periodNo: 1,
        labName: null,
        roomNo: null,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'M1',
        periodName: 'Operating Systems',
        semester: 4,
        periodNo: 2,
        labName: null,
        roomNo: null,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        staff: null,
      },
      {
        id: 'M2',
        periodName: 'Compiler Design',
        semester: 6,
        periodNo: 3,
        labName: null,
        roomNo: null,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'M3',
        periodName: 'Operating Systems',
        semester: 4,
        periodNo: 4,
        labName: null,
        roomNo: null,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'M4',
        periodName: 'OS Lab',
        semester: 4,
        periodNo: 5,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'M5',
        periodName: 'OS Lab',
        semester: 4,
        periodNo: 6,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
    ],
  },
  {
    day: 'Tuesday',
    periods: [
      {
        id: 'T0',
        periodName: 'Java Lab',
        semester: 6,
        periodNo: 1,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'T1',
        periodName: 'Data Structures Lab',
        semester: 6,
        periodNo: 2,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'T2',
        periodName: 'Data Structures Lab',
        semester: 6,
        periodNo: 3,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'T3',
        periodName: 'Data Structures Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 4,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'T4',
        periodName: 'Data Structures Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 5,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'T5',
        periodName: 'Data Structures Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 6,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
    ],
  },
  {
    day: 'Wednesday',
    periods: [
      {
        id: 'W0',
        periodName: 'LSD Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 1,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'W1',
        periodName: 'Data Structures Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 2,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'W2',
        periodName: 'Data Structures Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 3,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'W3',
        periodName: 'Data Structures Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 4,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'W4',
        periodName: 'Data Structures Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 5,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'W5',
        periodName: 'Data Structures Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 6,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
    ],
  },
  {
    day: 'Thursday',
    periods: [
      {
        id: 'TH0',
        periodName: 'Network Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 1,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'TH1',
        periodName: 'Data Structures Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 2,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'TH2',
        periodName: 'Data Structures Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 3,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'TH3',
        periodName: 'Data Structures Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 4,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'TH4',
        periodName: 'Data Structures Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 5,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'TH5',
        periodName: 'Data Structures Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 6,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
    ],
  },
  {
    day: 'Friday',
    periods: [
      {
        id: 'F0',
        periodName: 'OS Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 1,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'F1',
        periodName: 'Data Structures Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 2,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'F2',
        periodName: 'Data Structures Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 3,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'F3',
        periodName: 'Data Structures Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 4,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'F4',
        periodName: 'Data Structures Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 5,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
      {
        id: 'F5',
        periodName: 'Data Structures Lab',
        semester: 6,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 6,
        labName: 'Programming Lab',
        roomNo: 'MTB 209',
        staff: [{ staffID: 'flrvyfenuc', staffName: 'Ashik' }],
      },
    ],
  },
  {
    day: 'Saturday',
    periods: [
      {
        id: 'S0',
        periodName: null,
        semester: null,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 1,
        labName: null,
        roomNo: null,
        staff: null,
      },
      {
        id: 'S1',
        periodName: null,
        semester: null,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 2,
        labName: null,
        roomNo: null,
        staff: null,
      },
      {
        id: 'S2',
        periodName: null,
        semester: null,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 3,
        labName: null,
        roomNo: null,
        staff: null,
      },
      {
        id: 'S3',
        periodName: null,
        semester: null,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 4,
        labName: null,
        roomNo: null,
        staff: null,
      },
      {
        id: 'S4',
        periodName: null,
        semester: null,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 5,
        labName: null,
        roomNo: null,
        staff: null,
      },
      {
        id: 'S5',
        periodName: null,
        semester: null,
        batch: 'B',
        department: {
          id: 'wfvcwe',
          name: 'CSE',
        },
        periodNo: 6,
        labName: null,
        roomNo: null,
        staff: null,
      },
    ],
  },
];

export default timetableData;
